name: Test

on:
  - push
  - pull_request

jobs:

  php:
    name: PHP ${{ matrix.php }}

    strategy:
      fail-fast: false
      matrix:
        include:
          # Includes php7.4 - 8.3 and composer 2
          # https://github.com/actions/runner-images/blob/releases/ubuntu20/20241023/images/ubuntu/Ubuntu2004-Readme.md#php-tools
          - php: '7.4'
            os: ubuntu-20.04
          - php: '8.0'
            os: ubuntu-20.04
          - php: '8.1'
            os: ubuntu-20.04
          - php: '8.2'
            os: ubuntu-20.04
          - php: '8.3'
            os: ubuntu-20.04

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Use PHP ${{ matrix.php }}
      run: sudo update-alternatives --set php /usr/bin/php${{ matrix.php }}

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Test
      run: composer test
